### ISSUE TITLE
Problem running FreeHiC on demo data

### ISSUE THREAD

**Issue by jstansfield0** [yezhengSTAT/FreeHiC#1]
I'm trying to run FreeHiC on the demo data and I am getting the following error:

```
freeHiC.sh: line 145: /p/keles/yezheng/volumeA/Softwares/python3/bin/python3: No such file or directory
freeHiC.sh: line 150: /p/keles/yezheng/volumeA/Softwares/python3/bin/python3: No such file or directory
awk: cannot open 
```

It looks like some hard paths to the developers machine was left in the script?

**Comment by jstansfield0** [comment]
It also looks like something is going wrong with the BAM files as well.

```
[main] Real time: 0.002 sec; CPU: 0.000 sec
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "/home/mdozmorov/Downloads/FreeHiC/results/rawDataTraining/s1_alignment/GSM1215593_trimmedAndFiltered-TROPHOZOITES-XL-AGGG-L2_unmapped_trim_filter_2.sam".
```

**Comment by yezhengSTAT** [comment]
Hi there,
Sorry I don't know why I didn't receive a notification about the issue here. Thanks for point the hard-path errors out and I have updated it.
It is hard to diagnose the problem with the bam file based on the information you provided but there seems to be something wrong with the header from the input sam file.

Thanks,
Ye

**Comment by jstansfield0** [comment]
I tried FreeHiC again on some of our own fastq files and I'm getting errors with the BAM headers again. I was also still never able to get FreeHiC to complete on the demo data. Do you have any ideas for how to fix this?

```
[main] CMD: /usr/bin/bwa samse /home/john/share/Homo_sapiens_assembly19.fasta /home/john/share/results/rawDataTraining/s1_alignment/SRR6107806_2.sai /home/john/share/SRR6107806_2.fastq
[main] Real time: 2540.216 sec; CPU: 1142.304 sec
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "/home/john/share/results/rawDataTraining/s1_alignment/SRR6107806_2.sam".
[main] unrecognized command 'fastq'
[main] Version: 0.7.12-r1039
[main] CMD: /usr/bin/bwa aln -n 3 -o 1 -t 2 /home/john/share/Homo_sapiens_assembly19.fasta /home/john/share/results/rawDataTraining/s1_alignment/SRR6107806_unmapped_trim_filter_2.fastq
[main] Real time: 4.973 sec; CPU: 1.496 sec
[main] Version: 0.7.12-r1039
[main] CMD: /usr/bin/bwa samse /home/john/share/Homo_sapiens_assembly19.fasta /home/john/share/results/rawDataTraining/s1_alignment/SRR6107806_unmapped_trim_filter_2.sai /home/john/share/results/rawDataTraining/s1_alignment/SRR6107806_unmapped_trim_filter_2.fastq
[main] Real time: 0.018 sec; CPU: 0.004 sec
[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
[main_samview] fail to read the header from "/home/john/share/results/rawDataTraining/s1_alignment/SRR6107806_unmapped_trim_filter_2.sam".
awk: read error (Protocol error)
Traceback (most recent call last):
  File "/home/john/FreeHiC/scripts/joinEnds.py", line 165, in <module>
    with pysam.Samfile(args.readEnd1, "rb") as readEnd1, pysam.Samfile(args.readEnd2, "rb") as readEnd2:
  File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 985, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
sort: cannot read: /home/john/share/results/rawDataTraining/s2_validPairs/SRR6107806.validPairs: No such file or directory
cat: /home/john/share/results/rawDataTraining/s2_validPairs/SRR6107806.validPairs: No such file or directory
Traceback (most recent call last):
  File "/home/john/FreeHiC/scripts/freeHiC_main.py", line 2, in <module>
    import pyximport;pyximport.install()
ImportError: No module named 'pyximport'
cat: /home/john/share/results/rao2017/simuSequence/SRR6107806_1.fastq: No such file or directory
[bwa_seq_open] fail to open file '/home/john/share/results/rao2017/simuSequence/SRR6107806_1.fastq' : No such file or directory
[fread] Unexpected end of file
cat: /home/john/share/results/rao2017/simuSequence/SRR6107806_2.fastq: No such file or directory
[bwa_seq_open] fail to open file '/home/john/share/results/rao2017/simuSequence/SRR6107806_2.fastq' : No such file or directory
[fread] Unexpected end of file
open: No such file or directory
[bam_sort_core] fail to open file /home/john/share/results/rao2017/simuProcess/s1_alignment/SRR6107806_1.sorted.sam
open: No such file or directory
[bam_sort_core] fail to open file /home/john/share/results/rao2017/simuProcess/s1_alignment/SRR6107806_2.sorted.sam
mv: cannot stat '/home/john/share/results/rao2017/simuProcess/s1_alignment/SRR6107806_1.sorted.sam': No such file or directory
mv: cannot stat '/home/john/share/results/rao2017/simuProcess/s1_alignment/SRR6107806_2.sorted.sam': No such file or directory
awk: cannot open /home/john/share/results/rao2017/simuProcess/s2_validPairs/SRR6107806.validPairs (No such file or directory)
```

**Comment by yezhengSTAT** [comment]
Hello, 
Sorry to hear that! Let me see what I can help with.

It seems to me that the first error message "[bam_header_read] EOF marker is absent. The input is probably truncated." happens at the chimeric reads rescuing step which will run samtools to filter and get unmapped reads. There is something wrong with the header of the sam file that has just finished alignment. Can you check if the sam file look normal to you?
According to "[main] unrecognized command 'fastq'", it looks to me that your samtool version does not have the function "samtools fastq". Therefore, better download and install a more recent version of samtools (and maybe BWA as well :)).
For the rest of errors, please install the corresponding module for python.

As for the demo data, what kind of problems have you come across?

Best,
Ye

**Comment by jstansfield0** [comment]
When I check the bam files with samtools view in the results/rawDataTraining/s1_alignment folder I get the same EOF marker is absent error. I checked a different bam file and it displayed normally with samtools view. Also yes, the samtools fastq command seems to be absent, but my system is saying I have the most up to date version of samtools (Version: 0.1.19-96b5f2294a).

**Comment by yezhengSTAT** [comment]
Please refer to the "[Preparation](https://github.com/yezhengSTAT/FreeHiC#1-preparation)" section to install samtools of version >=1.3 and update BWA if needed.
